

name: Run UI Tests

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '10 7 * * *'
    - cron: '20 12 * * *'
    - cron: '35 18 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Скачиваем код проекта из репозитория
      uses: actions/checkout@v4

    - name: Устанавливаем Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Устанавливаем стабильный Google Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Устанавливаем библиотеки
      run: |
        pip install -r requirements.txt

    - name: Запуск нашего теста каталога плитки
      id: run_tests
      continue-on-error: true
      run: |
        pytest tests/unit/test_catalog_sorting.py --alluredir=allure-results

    - name: 📊 Установка Allure CLI
      if: always()
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -zxvf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: 📊 Генерация Allure-отчёта
      if: always()
      run: allure generate allure-results -o allure-report --clean


    - name: 📦 Упаковка артефактов для хостинга
      uses: actions/upload-pages-artifact@v3
      if: always()
      with:
        path: allure-report

    - name: 🚀 Деплой отчёта на GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      if: always()

    - name: 📲 Отправка пуш-нотификации в Telegram
      if: always()
      env:
        GH_STAGE_STATUS: ${{ steps.run_tests.outcome }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
      run: |
        python send_alert.py











